### ISSUE TITLE
Puppeteer Evaluation Error

### ISSUE THREAD

**Issue by fischer-felix** [theshanergy/whatbot#2]
When I execute whatbot using `npm run start`, I can scan the qr code successfully (not when using the new WhatsApp multi-device beta, but that's fine), but after I have done so, I get this error message:

```
/local/home/felix/Programming/whatbot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at __puppeteer_evaluation_script__:5:51
    at ExecutionContext._evaluateInternal (/local/home/felix/Programming/whatbot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/local/home/felix/Programming/whatbot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async Client.initialize (/local/home/felix/Programming/whatbot/node_modules/whatsapp-web.js/src/Client.js:145:9)
```
Any Idea why this would be (using the latest commit)?

**Comment by theshanergy** [comment]
Fixed in 109edbde64f42cb748abe6373fd94b6b05b81808
