### ISSUE TITLE
axios 429 too many requests issue

### ISSUE THREAD

**Issue by 5l1v3r1** [theshanergy/whatbot#6]
Whatsapp side works if the version is changed to 1.15.4 ot 1.15.3 but there is another proble with axios module. I think gpt-3 api has already started to limit the api calls and whenever axios calls a post request it gives an error of 429 like

GPT-3 REQUEST FAILURE Error: Request failed with status code 429
    at createError (C:\Users\User\Desktop\whatbot-master\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\User\Desktop\whatbot-master\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\User\Desktop\whatbot-master\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: 'https://api.openai.com/v1/engines/davinci/completions',
    method: 'post',

How can we fix that?

**Comment by 5l1v3r1** [comment]
ok figured out, my api expired couple of months ago. So i created a new account. The problem is sorted :)
