### ISSUE TITLE
Error authenticating WhatsApp

### ISSUE THREAD

**Issue by fraktosh** [theshanergy/whatbot#7]
Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.
    at LegacySessionAuth.getAuthEventPayload (/Users/sohamsaha/whatbot/node_modules/whatsapp-web.js/src/authStrategies/LegacySessionAuth.js:57:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.initialize (/Users/sohamsaha/whatbot/node_modules/whatsapp-web.js/src/Client.js:222:34)
![image](https://user-images.githubusercontent.com/34938615/180233074-ac8beef2-664b-4db0-9cbd-c3c091685cda.png)

**Comment by theshanergy** [comment]
Resolved by 4c1d884
