### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by murilloimparavel** [theshanergy/whatbot#8]
/Users/murilloalves/Desktop/bot/whatbot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'Socket')
    at __puppeteer_evaluation_script__:6:62
    at ExecutionContext._evaluateInternal (/Users/murilloalves/Desktop/bot/whatbot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/murilloalves/Desktop/bot/whatbot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.initialize (/Users/murilloalves/Desktop/bot/whatbot/node_modules/whatsapp-web.js/src/Client.js:172:9)

**Comment by theshanergy** [comment]
Fixed in 4c1d884
